/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stylus;

import com.wjduquette.joe.tools.ToolLauncher;
import stylus.tools.calendar.CalendarTool;
import stylus.tools.run.RunTool;
import stylus.tools.test.TestTool;

import java.util.*;

/**
 * The Stylus application launcher.  Launches various tool applications, provides
 * help, etc.
 */
public class App {
    /** The application name used in console output. */
    public static final String NAME = "stylus";

    //-------------------------------------------------------------------------
    // Main

    /**
     * The application's main routine.  The first argument is the name of
     * the tool to execute; the remainder are passed to the tool.
     * @param args The command-line arguments.
     */
    public static void main(String[] args) {
        var launcher = new ToolLauncher(NAME, List.of(
            CalendarTool.INFO,
            RunTool.INFO,
            TestTool.INFO
        ));

        try {
            launcher.launch(args);
        } catch (Exception ex) {
            System.err.println("Unexpected exception: " + ex);
            ex.printStackTrace(System.err);
        }
    }
}
